### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by redmusic27** [Toinane/container-ps#1]
Hello, sir. I want to offer something to you, do you need a new logo for your app? if you want i can make it to your liking

**Comment by Toinane** [comment]
Sorry for the late! You can if you want, I don't really need a logo in case we don't really see the logo when the app is launched, but yes 👍

**Comment by Toinane** [comment]
I've updated the logo myself today. If it's too ugly, you can make a new issue/PR for this 😄
For now I close this issue
