### ISSUE TITLE
There is no a issue !!! its a proposal 

### ISSUE THREAD

**Issue by ocuil** [Toinane/container-ps#9]
In the List.js file I add the next:
`{
              label: "Get Bash",
              id: container.id,
              click: event => {
                var childProc = require("child_process");
                childProc.exec(
                  'osascript -e \'tell application "Terminal" to activate do script "docker exec -ti \'' +
                    event.id +
                    "' bash\"'"
                );
                console.log(event.id);
              }
            }`

<img width="1004" alt="screenshoot" src="https://user-images.githubusercontent.com/8036150/72079186-bbab4d00-32fa-11ea-94c6-4a99ca71d4b9.png">

That let us create a new option to get a terminal inside the select docker ... 

I know that feature only works on mac devices and if the docker images have bash ... but maybe someone would like to improve that :-)

<img width="785" alt="screenshoot" src="https://user-images.githubusercontent.com/8036150/72079380-16dd3f80-32fb-11ea-81c1-c015b65ce01d.png">

Kind regards and thanks so much !!! 

I like very much that tool, I am learning !!!

Ale

**Comment by Toinane** [comment]
Hey @ocuil thank you for your proposal ! And really sorry for my late response..
I added it on the latest version 👍 You can see it here: [v1.3.0](https://github.com/Toinane/container-ps/releases/tag/1.3.0)
